### ISSUE TITLE
Installing zarrdataset

### ISSUE THREAD

**Issue by HappyHackingOrange** [TheJacksonLaboratory/zarrdataset#1]
### **Description:**

I attempted to follow the installation instructions for `zarrdataset` as provided in the documentation. However, I encountered an issue while using the command `python setup.py -e .`, which resulted in an error stating that the option -e is not recognized.

Undeterred, I proceeded to install the package using the following commands:

```
python setup.py build
python setup.py install
```

Despite successful execution, it appears that only the dependencies were installed, and the `zarrdataset` package itself is missing. I realized this when attempting to `import zarrdataset`.

Could you please provide guidance on the correct installation procedure or address this issue? Your assistance is greatly appreciated.

### **Environment:**

Python version: 3.7.7
Operating System: CentOS Linux 7

Thank you for your attention to this matter.

**Comment by fercer** [comment]
Hi @HappyHackingOrange, thanks for trying to install this package and raising this issue.
Certainly the installation instructions are wrong, and the actual way to install this package is using `pip`.

So try with the following command from within the _zarrdataset_ folder and let me know if that worked or not.
`
pip install -e .
`

**Comment by HappyHackingOrange** [comment]
Thank you for the quick response. That command didn't work, but entering `python -m pip install -e .` actually worked for me.

**Comment by fercer** [comment]
Great! I'll update the installation instructions to include this info. Thanks!
