### ISSUE TITLE
Incrementing the number of workers in the dataloader increase the number of times the dataset is iterated 

### ISSUE THREAD

**Issue by dveni** [TheJacksonLaboratory/zarrdataset#11]
Hi there!

I'm testing the library to iterate over chunks of a large dataset, however, I find that increasing the number of workers of the dataloader iterate over the dataset multiple times. Instead, I would expect that increasing nworkers would increase the number of processes used to load the data but iterate over the dataset just once.

A code example:
```
import zarrdataset as zds
import dask.array as da
from pathlib import Path
import zarr
from torch.utils.data import DataLoader
from tqdm import tqdm 

def zarr_setup(shape: tuple = (200, 3000, 3000), chunks: tuple = "auto"):
    data = da.random.random(shape, chunks=chunks)
    print(f"Data chunking: {data.chunksize}")
    path = f"test_{shape}_{chunks}.zarr"
    data.to_zarr(path, overwrite=True, component="0")
    return path

# patch_size = (100, 100, 100)
# patch_size = (50, 50, 50)
patch_size = (20, 289, 289)
# shape = (1000, 1000, 1000)
# shape = (100, 100, 100)
shape = (200, 3000, 3000)

path = zarr_setup(chunks=patch_size, shape=shape)
zarr_data = zarr.open(path, mode="r")
zarr_data['0'].info


my_patch_sampler = zds.PatchSampler(patch_size)


my_dataset = zds.ZarrDataset(dict(
    modality="images",
    filenames=zarr_data,
    source_axes="ZYX",
    data_group="0",
  ),
  patch_sampler=my_patch_sampler,
  return_positions=True,
  shuffle=True,
  progress_bar=False,
  draw_same_chunk=False,
  return_worker_id=False
  )

MAX_ITER = 2000
totals = {}
for batch_size in [50]:
    totals[batch_size] = {}
    for nworkers in tqdm([0,1,4,7, 10]):
        my_dataloader = DataLoader(my_dataset,
                                batch_size=batch_size,
                                num_workers=nworkers,
                                worker_init_fn=zds.zarrdataset_worker_init_fn)
        total1 = 0
        for i, (patch) in enumerate((my_dataloader)):
            if i == MAX_ITER:
                print(f"Break at {i}")
                break
            total1 += patch[-1].sum()
        totals[batch_size][nworkers] = (i, total1)
```

totals will show something like:

```
{50: {0: (19, tensor(8.3519e+08, dtype=torch.float64)),
  1: (19, tensor(8.3519e+08, dtype=torch.float64)),
  4: (79, tensor(3.3408e+09, dtype=torch.float64)),
  7: (139, tensor(5.8463e+09, dtype=torch.float64)),
  10: (199, tensor(8.3519e+09, dtype=torch.float64))}}
```
where we observe the total number of iterations (first integer) is nworkers times the number of iterations to finish the dataset.

Am I missing something or not setting up the dataset correctly? Any pointer is very welcome (:

Edit: Current environment:
```
python 3.11
"dask[complete]>=2024.9.1",
"numpy>=1.26.4",
"torch>=2.4.1",
"tqdm>=4.66.5",
"zarr>=2.18.3",
"zarrdataset>=0.2.0
```

**Comment by dveni** [comment]
Okay after some debugging I found out why. As I was iterating through the number of workers to see how the performance evolved increasing them, I ended up creating a copy of the entire dataset in each of the workers. Basically:
1. the dataset gets initialized with `nworkers=0`
2. increasing `nworkers` copies the entire dataset that was initialized with `nworkers=0` to each of the workers since `dataset._initialized` was set to True
4. Setting `dataset._initialized=False` after each nworkers iteration forces each of the workers to initialize the dataset, avoiding copying the previous initialization

I close the issue since the library is behaving as expected (maybe a warning on the workers if the dataset is already initialized at the first step could help?)

**Comment by fercer** [comment]
Hi @dveni, thanks for using `zarrdataset`!

You were faster than me trying to go through this behavior, and I'm happy that you were able to sort it out!

I think that enable re-initialization of the dataset is useful for benchmarking purposes, like your use case.
I'll keep it in mind for future releases.

Thank you!
